_wandb:
    value:
        cli_version: 0.22.3
        e:
            33ys1mn2hgwcwlm0f5pjedmuiq49fqq9:
                args:
                    - --dataset_name
                    - xes3g5m
                    - --fold
                    - "0"
                    - --use_trajectory
                    - "1"
                    - --traj_tensor_path
                    - embedding/polya_tensor.pt
                    - --traj_input_dim
                    - "5120"
                    - --dim_s
                    - "256"
                    - --size_m
                    - "50"
                    - --batch_size
                    - "128"
                    - --num_epochs
                    - "100"
                    - --learning_rate
                    - "1e-3"
                codePath: pykt-toolkit/train_test/cognitive_deep_irt_train.py
                codePathLocal: train_test/cognitive_deep_irt_train.py
                email: tjwns6952@naver.com
                executable: /home/sjin4861/solution-augmented-question-embedding/.venv/bin/python
                git:
                    commit: 8dcbe177a81c900febec9c371ac13f4233a96807
                    remote: https://github.com/oezyurty/KCQRL.git
                host: n71.gasi-cluster.cluster
                os: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28
                program: /home/sjin4861/solution-augmented-question-embedding/external/KCQRL/pykt-toolkit/train_test/cognitive_deep_irt_train.py
                python: CPython 3.12.11
                root: /home/sjin4861/solution-augmented-question-embedding/external/KCQRL/pykt-toolkit
                startedAt: "2025-11-29T04:03:04.712442Z"
                writerId: 33ys1mn2hgwcwlm0f5pjedmuiq49fqq9
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 13
            "4": 3.12.11
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
